image: golang:1.18

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

pages:
  script:
    - go get -u github.com/renatoathaydes/magnanimous
    - magnanimous -style monokai
  artifacts:
    paths:
      - target
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
