image: golang:1.18

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

pages:
  script:
    - go install github.com/renatoathaydes/magnanimous@0.11.1
    - magnanimous -style monokai
    - mv target public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
